apiVersion: v1
kind: Service
metadata:
  name: mysql-srv
spec:
  selector:                       # Selects any Pod with labels `app=polling-app,tier=mysql`
    app: mysql
  ports:
    - port: 3306
  clusterIP: None